image:
  file: .gitpod.dockerfile
ports:
  - port: 8080
  - port: 3306
    onOpen: ignore
tasks:
  - name: MySQL
    command: >
        mysqld --initialize-insecure;
        mysqld &
        sleep 5;
  - name: Apache
    init: composer install;
    command: >
        apachectl start;